### ISSUE TITLE
Missing quotes on GraphQLString args

### ISSUE THREAD

**Issue by kevinfez** [WeltN24/GraphQLicious#8]
Any query with a string argument would be missing quotations when the graphQL readable string is created. 

Example Query
```
func getSomething (id: String) -> Query {
    return Query(
        withRequest: Request(
            withAlias: "",
            name: "getSomething",
            arguments: [
                Argument(key: "id", value: **id**)
            ],
            fields: [
              _omitted_
            ]
        )
    )
}
```
Would output
```
{
  getSomething(id: **idWithoutQuotes**) {
    _omitted_
  }
}
```

In Argument.swift, changing case 1 of the GraphQLConvertible extension to check if the value[0] is String and returning a string with quotes around the value fixes it for my use cases. 

The original line
`return "\(key): \(values[0].asGraphQLString)"`

The replacement
```
if values[0] is String {
    return "\(key): \"\(values[0].asGraphQLString)\""
} else {
    return "\(key): \(values[0].asGraphQLString)"
}
```

**Comment by vittoriom** [comment]
Hi @kevinfez!
I see your point. To be honest, we added a `String` extension called `withQuotes` that you can use to add quotes to your string.
On Monday we'll discuss in the office whether it makes sense to leave it like it is right now or to automatically add quotes everytime you're passing a `String`, since it may be the most common scenario.

Thanks for raising the point and have a good weekend!

**Comment by kevinfez** [comment]
oh interesting, I had noticed the method but didn't expect I had to call it myself with the input!
Well that certainly is working, cool. 

I did have another question, could make another post if you'd prefer. 
But the question was simply if there is a mutation generator hidden in here too?

**Comment by vittoriom** [comment]
Hi @kevinfez, what do you mean exactly with "mutation generator"?

**Comment by kevinfez** [comment]
They're very similar to queries, just a different keyword and a few other small distinctions. 
This is the best source I've been able to find on how they're supposed to be structured:
https://facebook.github.io/relay/graphql/mutations.htm

**Comment by vittoriom** [comment]
Ah, I see! 
No, we don't have mutations in GraphQLicious at the moment. I'll create a separate issue for that :)

**Comment by vittoriom** [comment]
Hi @kevinfez,

I'll close this issue since we discussed internally the benefits and the cons of automatically adding quotes for String values.

The thing is, that we need to keep in mind that enums are also allowed in GraphQL.

Something like this:

```
query(category: politics) {
  id
}
```

wouldn't be possible if we always added quotes to strings.
For this, I would say it's better to use `withQuotes` when needed, and leave the implementation as it is right now.

Thanks again for opening the issue, I hope this comment clarifies the motivations behind the choice.

**Comment by kevinfez** [comment]
I guess my final 2 cents would be that a string acting as a string would align most with the 'principle of least astonishment'. And instead having a method such as 'asEnum' that removes the quotes when necessary would probably be a bit more intuitive for someone new to his component. 
But modifying the existing example in the readme to include a string argument would also prove very helpful.

**Comment by joemcbomb** [comment]
Hi @kevinfez 
thank you for your feedback. What you say makes sense to me. I think we can still chew on that for a while. :)
But no matter the outcome of that I'll gladly provide an example in the readme asap.

Cheers

**Comment by vittoriom** [comment]
Hi @kevinfez, we listened to your suggestion and now string arguments are quoted by default. Enums are also supported and not quoted of course, unless explicitly intended.

Thanks again!

**Comment by navasiloy** [comment]
Hey
can you drop a snipped how to get rid of string quotes?

**Comment by kevinfez** [comment]
they have a .withoutQuotes extension on String if that's what you're looking for.
otherwise they also have an example on how to do quote-less enums in the readme, I'll snip out the example for you.
`enum customeEnum: String, ArgumentValue {case This = "this"
case That = "that"
}`

`enum customEnum: String, ArgumentValue {
  case This = "this"
  case That = "that"

  private var asGraphQLArgument: String {
    return rawValue // without quotes
  }
}`

**Comment by navasiloy** [comment]
Thank you :)
